### ISSUE TITLE
Feature Request:  apply 6 lens automatically during build district

### ISSUE THREAD

**Issue by vttale** [astog/MoreLenses#9]
It'd be spectacular if when I picked to build an Industrial District or Entertainment District the build screen has the 6 tile lens applied.  In a perfect world it would have both 6 and 9 but I've not thought enough about how to do that best.

**Comment by astog** [comment]
This would be part of my effort to improve the built in district lens that gets applied when constructing a district.

**Comment by astog** [comment]
Super late to this, but better late than never. I think this should be done in Lens Augmented Map Tacks (LAMP) rather than here since when building a district in a specific city we just want max adjacency. But the map tack placement usually is done for best civilization scope placement, zoomed out and all.
